import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import LoginBtn from './LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import LogoutBtn from './LogoutBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // * server component 에서 사용 가능
  let session = await getServerSession(authOptions);

  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white p-[20px]">
          <Link href="/" className="mr-[10px] font-bold text-black">
            Appleforum
          </Link>
          <Link href="/list" className="mr-[10px] text-black">
            List
          </Link>
          <Link href="/write" className="mr-[10px] text-black">
            글쓰기
          </Link>
          {session ? <LogoutBtn username={session.user?.name} /> : <LoginBtn />}
        </div>
        {children}
      </body>
    </html>
  );
}
